### ISSUE TITLE
Why doesn't this work on IE?

### ISSUE THREAD

**Issue by mjmaurer** [andywer/use-inline-memo#20]
Thank you so much for this repo!

I'm trying to understand how this works, and I think understanding why it doesn't work on IE might help. I saw the FAQ, but I'm still a bit lost.

**Comment by andywer** [comment]
Thanks, @mjmaurer. Have a look at the readme: <https://github.com/andywer/use-inline-memo#usage>

This library does work in IE, but only when explicitly passing the method names you intend to call on the object returned by `useInlineMemo(keys)`. In half-way modern browsers you can just call `useInlineMemo()` without any arguments and get an object that you can call arbitrary methods on, because it will return a [`new Proxy({ /* … */ })`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) that can react to any calls on that object.

This way it can provide an object to you with all the methods you need without even knowing yet what methods you will need. As IE does not provide `Proxy`, that approach does not work on IE and you need to tell the library upfront what methods you are going to need, so it can return an object with all these methods.

Hope that makes it a bit clearer!
